### ISSUE TITLE
Duplicated quiz words

### ISSUE THREAD

**Issue by lauradekker** [AdvPyS23/LanguageLearner#2]
When running the test function I noticed that some words are asked more than once. Could you implement a function that does not allow the words to return to the pool they are chosen from?

**Comment by vespaquinn** [comment]
Hi Laura,
Thanks for bringing up the issue! We've changed some parameters to that now if you select a quiz set of 10 words of a certain topic, but there are only, say 5, words in that topic, the quiz will be of length 5, instead of outputting 5 duplicated words :)
